Feature/jc 627 blackjack by dice
saritasa-nest/camp-js-2024-maxim-sherstkov pull request #2
Opened 2024-07-11 10:57 UTC by sherstkov

Developed a page for a blackjack game, but with dice using the `observer` pattern.

2024-07-16 05:11 UTC, karbik-creator commented on apps/vanilla/src/pages/blackjack/ts/core/diceGenerator.ts
> +	 */
You can omit comments to constructor
```suggestion
```

2024-07-16 05:16 UTC, karbik-creator commented on apps/vanilla/src/pages/blackjack/ts/core/player.ts
> + */
```suggestion
/**
 * Player class that tracks dice results and win status.
 */
```

2024-07-16 05:17 UTC, karbik-creator commented on apps/vanilla/src/pages/blackjack/ts/core/player.ts
> +	public results$: Publisher<number[]> = new Publisher<number[]>();
```suggestion
	/**
	 * Shows the result of all rolls for current player.
	 */
	public readonly results$ = new Publisher<number[]>();
```

2024-07-16 05:23 UTC, karbik-creator commented on apps/vanilla/src/pages/blackjack/ts/core/publisher.ts
> +	public unsubscribe(s: TSubscriber<T>): void {
Let's improve naming `s` -> `subscriber`
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#s-i-d

2024-07-16 05:31 UTC, karbik-creator commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +	private readonly players: Player[];
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#prefer-tuple-properties
```suggestion
	private readonly players: radonly Player[];
```

2024-07-16 05:37 UTC, karbik-creator commented on apps/vanilla/src/pages/blackjack/ts/main.ts
> +const game = new Game(playerCount, 6, playersResultsElements, debugElement);
Let's put the number into a descriptive constant

2024-07-16 09:09 UTC, golovachev-yaroslav requested changes

2024-07-16 09:09 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/blackjack/ts/core/publisher.ts
> +		this.subscribers.forEach(sub => sub.update(message));
Same with `sub`, it would be better to renmae as `subscriber`.

2024-07-16 09:09 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/blackjack/index.css
> +@import url("../../global/index.css");
This approach not so good. Much better to use `<link rel="stylesheet">`
https://www.reddit.com/r/css/comments/12ow6b5/is_it_bad_practice_to_use_a_bunch_of_import_rules/

2024-07-16 09:41 UTC, andrey-gazzaev requested changes
![image](https://github.com/user-attachments/assets/19089d73-bc91-46fe-abc5-7e49c83d5c4e)
It looks like your game has no end. Let's handle this case. In addition, it is not possible to start your game from the beginning. 

What if I want to get even?

2024-07-16 09:41 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/diceGenerator.ts
> +	 */
In fact, the class documentation is the constructor documentation. This is because the class name is also a constructor function.

2024-07-16 09:41 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +	private readonly debugDisplayer: DebugDisplayer;
I'm not sure that debugging functions should be in PR code. In fact, this is the same as console.log

2024-07-16 09:41 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +	public constructor(playersCount: number, diceSidesCount: number, playerElements: HTMLElement[], debugElement: HTMLElement) {
Let's make the parameters a separate object https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#avoid-ordered-params-in-constructorsfunctions

2024-07-16 09:41 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/views/resultDisplayer.ts
> +		const total = results.reduce((a, b) => a + b, 0);
```suggestion
		const total = results.reduce((acc, curr) => acc + curr, 0);
```

2024-07-16 09:41 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/diceGenerator.ts
> +		return result;
Do you need to return a value in a method?

2024-07-16 09:41 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +				/* Unsubscribe all players from DiceGenerator */
Do you have any player subscriptions during initialization?

2024-07-16 09:41 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/player.ts
> +		}
```suggestion
			this.winStatus$.notify(total >= 21);
```

2024-07-16 09:41 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/player.ts
> +		this.results$.notify(this.diceResults);
Why do you need to duplicate data if `result$` already stores all the rolled dice? You can subscribe to changes in the result and work with the data stored by `result$`

2024-07-16 09:41 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +			const winnerDisplayer = new WinnerDisplayer(playerElements[index]);
I think it would be correct to unsubscribe from everyone and sign when the game is over

2024-07-16 09:45 UTC, sherstkov commented on apps/vanilla/src/pages/blackjack/index.css
> +@import url("../../global/index.css");
Yes, but I can't link it like that because of how Vite has assembled our vanilla project. We can't access files on the outside level like this:
```html
<link rel="stylesheet" href="../../global/index.css" />
```
That's why we put the `assets` folder inside the `pages` folder. Can we keep `@import` for now?

2024-07-16 10:15 UTC, sherstkov commented on apps/vanilla/src/pages/blackjack/ts/core/diceGenerator.ts
> +		return result;
Yes, for `debugPublisher` 
```ts
```

2024-07-16 10:18 UTC, sherstkov commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +	private readonly debugDisplayer: DebugDisplayer;
I think we need it for task purposes.  But I'm not entirely sure. Let's keep this logic for now.

2024-07-16 12:36 UTC, karbik-creator commented on apps/vanilla/src/pages/blackjack/ts/main.ts
> +const playersResultsElements = Array.from(playersResultsHTMLCollection) as HTMLElement[];
You can use `document.querySelectorAll<your type>()` to avoid using `as`

2024-07-18 03:59 UTC, golovachev-yaroslav requested changes

2024-07-18 03:59 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/blackjack/ts/main.ts
> +const historyElement = <HTMLElement>document.getElementsByClassName('history-rolls')[0];
`querySelectorAll` is more useful when using more complex selectors.
Example: `document.querySelectorAll("div.note, div.alert")`

2024-07-18 03:59 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/blackjack/ts/main.ts
> +document.getElementById('roll-dice')?.addEventListener('click', () => {
It looks like missed remnoveEventListener
https://developer.mozilla.org/ru/docs/Web/API/EventTarget/removeEventListener

2024-07-18 03:59 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/blackjack/index.css
> +@import url("../../global/index.css");
Ok

2024-07-18 05:50 UTC, sherstkov commented on apps/vanilla/src/pages/blackjack/ts/main.ts
> +const historyElement = <HTMLElement>document.getElementsByClassName('history-rolls')[0];
Yes, but I realized that `history-rolls` should be an id, because where is no styles for this element.

2024-07-22 03:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/index.html
> +		<div>
```suggestion
		<section>
```
I think you can divide it into sections

2024-07-22 03:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +	playersCount: number;
```suggestion
	readonly playersCount: number;
```

2024-07-22 03:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +	private checkWinStatus(diceResults: number[], player: Player): void {
```suggestion
	private checkWinStatus(diceResults: readonly number[], player: Player): void {
```

2024-07-22 03:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/main.ts
> +const game = new Game(gameConstructorData);
```suggestion
const DEFAULT_DICE_COUNT = 6;
const game = new Game( {
	playersCount,
	diceSidesCount: DEFAULT_DICE_COUNT,
	playerElements: playersResultsElements,
	historyElement,
	diceButtonElement,
});
```

2024-07-22 03:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/utils/subscriber.ts
> +	 */
```suggestion
	 * Method to receive a notification of type T from the publisher.
	 * @param message - ?
	 */
```

Is it necessary to mention in the documentation the type of message that will be sent to the method?

2024-07-22 03:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +	}
This method does more than just check the winner. Let's split the implementation

2024-07-22 03:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +		this.bondedPlayTurn = this.playTurn.bind(this);
```suggestion
		this.bondedPlayTurn = this.playTurn.bind(this);
```
It's strange to use another method to bind a class method that already exists in this class. Let's use direct binding

2024-07-22 03:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/index.html
> +    <title>Document</title>
```suggestion
    <title>BlackJack</title>
```

2024-07-22 04:07 UTC, golovachev-yaroslav requested changes

2024-07-22 04:07 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/blackjack/index.css
> +  background-color: crimson;
Please use css variables.

2024-07-22 04:07 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +	diceButtonElement: HTMLElement;
HTMLElement is a common type. It looks like there should be `HTMLButtonElelent`,

2024-07-22 04:07 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +	historyElement: HTMLElement;
Maybe HTMLDivElement?

2024-07-22 07:34 UTC, golovachev-yaroslav approved these changes

2024-07-24 06:10 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +		this.players.forEach((player, index) => {
Please create separate method

2024-07-24 06:11 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +		this.turnGenerator$.subscribe({
The same about separate method

2024-07-24 06:14 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/blackjack/ts/core/game.ts
> +			this.rollDiceButton?.removeEventListener('click', this.bondedPlayTurn);
Why do we use type checking for rollDiceButton? its type is HTMLButtonElement

2024-07-24 06:14 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/blackjack/ts/core/player.ts
> + *
empty line

2024-07-24 06:19 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/blackjack/ts/utils/subscriber.ts
> +export type TSubscriber<T> = {
What means T in contractions? Usually we use this approach to generic

2024-07-24 06:24 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/blackjack/ts/views/historyDisplayer.ts
> +		const currentContent = this.historyElement.innerHTML;
Can we avoid interaction with DOM? May be we can use some var to display content?

2024-07-24 06:26 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/blackjack/ts/main.ts
> +const diceButtonElement = <HTMLButtonElement>document.getElementById('roll-dice');
Please remove type assertion - in this case you have incorrect type and can get runtime error

2024-07-24 10:06 UTC, andrey-gazzaev reviewed
Let's improve the code documentation a little

2024-07-24 10:06 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/core/player.ts
> +	 */
```suggestion
	/** @inheritdoc */
```

2024-07-24 10:06 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/views/historyDisplayer.ts
> + * HistoryDisplayer class that updates the UI with all dice rolls for historyging.
Does the class itself update the UI or does the user of this class use its capabilities? Are you sure that the documentation reflects the essence of the class?

2024-07-24 10:06 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/ts/views/resultDisplayer.ts
> + * ResultDisplayer class that updates the UI with player results.
same

Read this [article ](https://deno.com/blog/document-javascript-package) for good documentation practices

2024-07-29 15:21 UTC, sherstkov commented on apps/vanilla/src/pages/blackjack/ts/views/historyDisplayer.ts
> +		const currentContent = this.historyElement.innerHTML;
I'm not quite sure what you mean. we can create a separate variable to store the roll results and use a separate method to display those results. Is that better?
```ts
public update(result: number): void {
this.historyContent = this.historyContent ? `${this.historyContent}, ${result}` : `${result}`;
this.render();
}

private render(): void {
this.historyElement.innerHTML = this.historyContent;
}
```

2024-07-30 03:45 UTC, golovachev-yaroslav approved these changes

2024-07-30 04:27 UTC, andrey-gazzaev approved these changes

2024-07-31 05:14 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/blackjack/ts/views/historyDisplayer.ts
> +		const currentContent = this.historyElement.innerHTML;
I'm sorry, it's only JS step, you can leave it as is. And if you set value as string you can use textContent

2024-07-31 05:17 UTC, sherstkov commented on apps/vanilla/src/pages/blackjack/ts/views/historyDisplayer.ts
> +		const currentContent = this.historyElement.innerHTML;
ooh, i got you :+1:

2024-08-05 07:29 UTC, merged