Feature/jc 659 anime list management
saritasa-nest/camp-js-2024-maxim-sherstkov pull request #4
Opened 2024-07-29 10:01 UTC by sherstkov

Added anime list management features like: type filters, `title_eng`, `aired.start`, `status` sorting and pagination.

I also have a problem with the loader state. I'd be happy if someone could help me solve it. 

So I have `isLoading` observable inside of service and change it on request. I use it inside of dashboard component and show in template. And it's all fine, but when I move `camp-anime-table` to `else`, the scope loader becomes permanent and the loading state never changes.

2024-07-30 11:44 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/anime-dashboard.component.html
> +	</mat-paginator>
```suggestion
	<camp-anime-table class="anime-table" [animeList]="animeList$ | async" />
	
	<mat-paginator
		class="pagination"
		[length]="animeTotal"
		[pageSize]="pageSize$ | async"
		[showFirstLastButtons]="true"
		[pageSizeOptions]="[5, 10, 15]"
		[pageIndex]="currentPage$ | async"
		(page)="handlePageEvent($event)"
		[disabled]="isLoading$ | async"
	/>
```

2024-07-30 11:44 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/anime-dashboard.component.html
> +						[(ngModel)]="searchValue"
```suggestion
						[(ngModel)]="searchValue"
```

Let's use `formControls`

2024-07-30 11:44 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/anime-dashboard.component.html
> +			<form class="search-form" (ngSubmit)="onSearch()">
https://htmlacademy.ru/blog/html/search

Not long ago a new tag appeared

2024-07-30 11:44 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/anime-dashboard.component.ts
> +	protected animeTypes = Object.values(AnimeType);
```suggestion
	protected readonly isLoading$ = this.animeService.observableIsLoading$;

	/** Anime count. */
	protected readonly animeTotal = AnimeParams.defaultValues.animeTotal;

	/** Search input value. */
	protected readonly searchValue = AnimeParams.defaultValues.searchValue;

	/** Anime type values. */
	protected readonly animeTypes = Object.values(AnimeType);
```

We follow the immutability approach; most often, class fields are immutable. Let's make decisions that will be based on this principle

2024-07-30 14:24 UTC, sherstkov commented on apps/angular/src/app/features/anime-dashboard/anime-dashboard.component.html
> +			<form class="search-form" (ngSubmit)="onSearch()">
Angular didn't know yet :(
```
1. If 'search' is an Angular component, then verify that it is included in the '@Component.imports' of this component.
```

I can use `CUSTOM_ELEMENTS_SCHEMA` in the component, but should I?

2024-07-31 04:30 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/anime-dashboard.component.html
> +			<form class="search-form" (ngSubmit)="onSearch()">
lol

2024-07-31 04:55 UTC, sherstkov commented on apps/angular/src/app/features/anime-dashboard/anime-dashboard.component.ts
> +	protected animeTypes = Object.values(AnimeType);
Hope i get it right :crossed_fingers:

2024-08-01 03:30 UTC, andrey-gazzaev requested changes

2024-08-01 03:30 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/components/anime-table/anime-table.component.ts
> +	@Input() public animeList: readonly Anime[] | null = [];
```suggestion
	@Input() 
	public animeList: readonly Anime[] = [];
```

Why might the value be `null`? Why does this component even care that the value might be different from the entity the component is working with?

Leave the data handling to the consumers of this component.

2024-08-01 03:30 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/components/anime-table/anime-table.component.ts
>  	protected readonly displayedColumns = ['image', 'englishTitle', 'japaneseTitle', 'airedStart', 'type', 'status'] as const;
Let's use the enum

2024-08-01 03:30 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/components/anime-table/anime-table.component.ts
> +	 */
```suggestion
	/**
	 * Handles the sort change.
	 * @param sort - New sort value.
	 */
	 protected handleSortChange(sort: Sort): void
```

2024-08-01 03:30 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +	private readonly destroy$ = new Subject<void>();
let's use [destroyRef ](https://angular.dev/api/core/DestroyRef) with [takeUntilDestroyed](https://angular.dev/api/core/rxjs-interop/takeUntilDestroyed#)

2024-08-01 03:30 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +	private readonly animeParams$: BehaviorSubject<AnimeParams> = new BehaviorSubject(new AnimeParams());
```suggestion
	private readonly _animeParams$ = new BehaviorSubject<AnimeParams>(new AnimeParams());
```

2024-08-01 03:30 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +	public readonly observableAnimeParams$ = this.animeParams$.asObservable();
```suggestion
	public readonly animeParams$ = this.animeParams$.asObservable();
```

2024-08-01 03:30 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +	private readonly isLoading$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
```suggestion
	private readonly isLoading$ = new BehaviorSubject(false);
```

2024-08-01 03:30 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +	public readonly observableIsLoading$ = this.isLoading$.asObservable();
same

2024-08-01 03:30 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +		);
You have an abstraction leak. In your service, there is work with URL query, with http parameters and with models and DTOs.

These are all entities of different levels:
URL query is the UI level
Model is the domain level
http params and Dto are the response level

2024-08-01 03:30 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +export class AnimeService implements OnDestroy {
```suggestion
export class AnimeService {
```
The service has no life hooks

2024-08-01 03:30 UTC, andrey-gazzaev commented on apps/angular/src/core/services/query-params.service.ts
> +	public getHttpParams(params: AnimeParams): HttpParams {
```suggestion
	public getQueryParams(params: AnimeParams): HttpParams {
```
Why do you use response level terms at the UI level?

2024-08-01 03:30 UTC, andrey-gazzaev commented on apps/angular/src/core/services/query-params.service.ts
> +		return new HttpParams({ fromObject: animeParams });
Judging by the name, the service can work with any data structures that need to be written in the URL, but in fact this service only works with AnimeParams

2024-08-01 03:30 UTC, andrey-gazzaev commented on libs/core/mappers/based-params.mapper.ts
> +	export function toArrayAnimeType(array: string[]): AnimeType[] {
```suggestion
	export function toAnimeType(array: readonly string[]): AnimeType[] {
```

2024-08-01 03:30 UTC, andrey-gazzaev commented on libs/core/mappers/based-params.mapper.ts
> +import { AnimeParamsDto } from '../dtos/based-params.dto';
Rename the file

2024-08-01 03:30 UTC, andrey-gazzaev commented on libs/core/mappers/based-params.mapper.ts
> +			model.filterByType.map(AnimeTypeMapper.toDto).join(',') :
```suggestion
			model.filterByType.map((type) => AnimeTypeMapper.toDto(type)).join(',') :
```
Be careful, in this case you have lost the context

2024-08-01 03:30 UTC, andrey-gazzaev commented on libs/core/models/based-params.ts
> +	public static readonly defaultValues = {
```suggestion
	public static readonly DEFAULT_VALUE = {
```

2024-08-01 03:30 UTC, andrey-gazzaev commented on libs/core/models/based-params.ts
> +export class AnimeParams extends Immerable {
```suggestion
export class AnimeQuery extends Immerable {
```
It's similar to query

2024-08-01 03:30 UTC, andrey-gazzaev commented on libs/core/models/based-params.ts
> +	public readonly filterByType: AnimeType[];
```suggestion
	public readonly filterByTypes: readonly AnimeType[];
```

2024-08-01 03:30 UTC, andrey-gazzaev commented on libs/core/models/based-params.ts
> +	public constructor(data: Partial<AnimeParamsData> = {}) {
```suggestion
	public constructor(data: Partial<AnimeParamsData> = AnimeParams.DEFAULT_VALUE ) {
	super();
		this.pageIndex = data.pageIndex;
		this.pageSize = data.pageSize;
		this.searchValue = data.searchValue;
		this.sortOrder = data.sortOrder;
		this.filterByType = data.filterByType;
```

2024-08-01 03:30 UTC, andrey-gazzaev commented on libs/theme/src/reset.css
> +}
You can use https://meyerweb.com/eric/tools/css/reset/

2024-08-01 03:37 UTC, sherstkov commented on apps/angular/src/core/services/anime.service.ts
> +	private readonly destroy$ = new Subject<void>();
> let's use [takeUntilDestroyed](https://angular.dev/api/core/rxjs-interop/takeUntilDestroyed#)

Yes, but `takeUntilDestroyed` in the developer preview. Is this OK to use now?

2024-08-05 04:16 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/components/anime-table/anime-table.component.ts
> +	protected readonly animeEnum = AnimeEnum;
What is enum in the context of a table? Maybe these are table columns?

2024-08-05 04:16 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/components/anime-table/anime-table.component.ts
> +		});
Why does your table process sorting or filter values? Shouldn't the table just show the content?

2024-08-05 04:16 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/components/anime-table/anime-table.component.ts
> +		this.pageParamsService.changeSortParams(sort);
same

2024-08-05 04:16 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/components/anime-table/anime-table.component.ts
> +		this.pageParamsService.changeSortParams(sort);
The fact is that this architecture is not obvious. You use services that work with filters from different pieces of code. Thus, you disrupt the flow of data from component to component. 

Now you can't guarantee that the service data will not be changed by any other component with this approach.

2024-08-05 04:16 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +			}),
same

2024-08-05 04:16 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +			}),
Let's make the data transfer from the component to the service component explicit.

2024-08-05 04:16 UTC, andrey-gazzaev commented on apps/angular/src/core/services/page-params.service.ts
> +export class PageParamsService {
You are still using a too abstract name for the service, although it only works with anime parameters

2024-08-05 04:16 UTC, andrey-gazzaev commented on apps/angular/src/core/services/page-params.service.ts
> +	}
Why do you need it?

2024-08-05 04:16 UTC, andrey-gazzaev commented on libs/core/models/sort-order.ts
> +};
How is order different from direction?

2024-08-05 14:40 UTC, sherstkov commented on apps/angular/src/core/services/anime.service.ts
> +			}),
What do you think of this approach? Now we are more explicit that we are using params as an observable and not changing params.
```suggestion
private readonly animeParams$ = this.pageParamsService.getAnimeParams();
```

2024-08-05 14:59 UTC, sherstkov commented on apps/angular/src/core/services/page-params.service.ts
> +	}
This way it's clear to see how sorting changes. It's basically 3 states: empty sort, ascending sort and descending sort. I made the docs more explicit about this.

2024-08-06 02:41 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +			}),
You do not need to store filter parameters in the service at all. Just pass them as a method argument

2024-08-06 02:45 UTC, andrey-gazzaev commented on apps/angular/src/core/services/page-params.service.ts
> +	}
Why can't you just use a flat object?
```{ page, pageSize, search, types, field, direction }```

2024-08-06 03:07 UTC, andrey-gazzaev reviewed
Before we go any further, let's fix the problem in Anime Service

2024-08-06 03:07 UTC, andrey-gazzaev commented on libs/core/mappers/anime-params.mapper.ts
> +	}
Can this method work with other structures? Except Anime Query. If yes, then it looks like a utility function

2024-08-06 03:07 UTC, andrey-gazzaev commented on libs/core/models/sort-order.ts
> +	direction: SortDirection;
```suggestion
	/** Sorting field by which data is to be sorted (like 'name' or 'date'). */
	readonly active: string;

	/** Sorting direction (ascending, descending or no order).  */
	readonly direction: SortDirection;
```

2024-08-08 03:19 UTC, andrey-gazzaev approved these changes
Well done 🔥

2024-08-08 03:19 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/anime-dashboard.component.html
> +		<camp-basic-progress-spinner></camp-basic-progress-spinner>
```suggestion
		<camp-basic-progress-spinner />
```

2024-08-08 03:19 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-dashboard/components/anime-table/anime-table.component.html
> +	<p class="anime-list__empty-message"> No anime to display. </p>
https://material.angular.io/components/table/api#MatNoDataRow

2024-08-09 08:35 UTC, karbik-creator commented on apps/angular/src/app/features/anime-dashboard/components/anime-table/anime-table.component.ts
> +	public sortChange = new EventEmitter<Sort>();
Please add readonly
https://wiki.saritasa.rocks/frontend/frameworks/angular/best-practices#prefer-readonly-outputs

2024-08-09 08:36 UTC, karbik-creator commented on apps/angular/src/core/services/anime.service.ts
> +		const animeParams = { ...AnimeParamsMapper.toDto(params) };
```suggestion
		const animeParams = AnimeParamsMapper.toDto(params);
```

2024-08-09 08:40 UTC, karbik-creator commented on apps/angular/src/core/services/page-anime-params.service.ts
> +		this.changeAnimeParams({ pageIndex: paginationParams.pageIndex, pageSize: paginationParams.pageSize });
```suggestion
		this.changeAnimeParams(paginationParams);
```

2024-08-09 10:47 UTC, karbik-creator approved these changes

2024-08-12 11:44 UTC, pavelzadorin-saritasa approved these changes

2024-08-12 12:21 UTC, merged