Feature/jc 678 authorization
saritasa-nest/camp-js-2024-maxim-sherstkov pull request #5
Opened 2024-08-08 17:26 UTC by sherstkov

Register and login pages, refresh token interceptor, logged in guard.

2024-08-09 00:59 UTC, viktor-sakhno-saritasa requested changes

2024-08-09 00:59 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/authentification/auth.component.css
> +}
It's not clear for me for what element this styles is applied? Could you add doc?

2024-08-09 00:59 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/authentification/auth.component.ts
> +	}
Let's rewrite this to signals

2024-08-09 00:59 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/authentification/login/login.component.html
> +			<input matInput formControlName="email" type="email" >
I recommend using another way to use reactive forms in the template.
```suggestion
			<input matInput [formControl]="loginForm.controls.email" type="email" >
```
It guarantees us, if our control name will change, VS Code helps us to show error in the HTML template, otherwise, we can build the app without any errors, but, actually, our code is broken.

2024-08-09 00:59 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/authentification/login/login.component.html
> +			<button mat-stroked-button type="submit" [disabled]="loginForm.invalid">Login</button>
Do I understand correctly that we can continue to click on the button while the authorization request is being process to the backend? Let's improve it?

2024-08-09 00:59 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/authentification/login/login.component.ts
> +						this.formErrorService.renderServerErrors(this.loginForm, error);
It's bad practice to use such words inside our client code (UI components, models, etc.). We should move such things to the service or just improve function name and avoid such words like 'http', 'server', etc.

2024-08-09 00:59 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/authentification/login/login.component.ts
> +					return of(null);
Do you think, it's a good solution to hide errors that isn't `ApiError`? You can face with some execution errors, which were thrown inside observable.
```suggestion
					throw Error(...)
```

2024-08-09 00:59 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/authentification/login/login.component.ts
> +	}
Actually, for some simple things, we can avoid using rxjs, and can just declare a variable like `hidePassword = false`; and just change the value by clicking on the toggle button. Also, I think signals would be better here.

2024-08-09 00:59 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/guards/already-logged-in.guard.ts
> +export class AlreadyLoggedInGuard implements CanActivate, CanActivateChild {
Angular and our teams prefer a functional way to declare guards, resolvers, etc. It would be better to use functional approach here too. Check this [link](https://medium.com/ngconf/functional-route-guards-in-angular-8829f0e4ca5c), pls

2024-08-09 00:59 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +	private readonly http: HttpClient = inject(HttpClient);
We can omit types for explicit things
```suggestion
	private readonly http = inject(HttpClient);
```

2024-08-09 00:59 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +			}),
I believe we don't need to cache response from calling some BE endpoints in which we aren't sure. I mean, `register`, `login` we will call not often, so we can remove `shareReplay` and be safely.

2024-08-09 00:59 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +	 */
```suggestion
	/**
	 * Refreshes the user secret.
	 * @param secret User secret.
	 */
```

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa requested changes

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/authentification/auth.component.css
> +  gap: 100px;
Do you need this gap?

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/authentification/login/login.component.ts
> +	private readonly formBuilder: FormBuilder = inject(FormBuilder);
This type annotation is unnecessary. It's okay to name `fb`.
```suggestion
	private readonly fb = inject(FormBuilder);
```

Also, we're usually using `NonNullableFormBuilder` and explicitly setting `null` for some fields if they're nullable.

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/authentification/login/login.component.ts
> +				takeUntilDestroyed(this.destroyRef),
Prefer placing `takeUntilDestroyed(this.destroyRef),`. In the current case, there is no issue, but sometimes there can be `switchMap` or `cobineLatestWith` operators that will still fire.

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/authentification/register/register.component.html
> +				</button>
Never seen that button toggles password visibility in both inputs. Let's extract it into component `input-password`, where we will toggle password visibility locally for each input.

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/authentification/register/register.component.ts
> +	 *  */
```suggestion
	 */
```

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/form-error.service.ts
> +	};
You can extract it to variable. Also prefer using `Record<>`, its a bit cleaner 
```suggestion
	const ERROR_MESSAGES: Record<string, string> = {
		general: 'Something went wrong. Please try again later.',
		required: 'This field is required.',
		email: 'Enter a valid email address.',
		minlength: `Below the minimum length required for this field.`,
		maxlength: `Exceeds the maximum length of this field.`,
		passwordMatch: 'Passwords do not match.',
	};
```

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/notification.service.ts
> +	protected readonly _snackBar: MatSnackBar = inject(MatSnackBar);
Not sure why we need it `protected` and `_`-prefix. 

Can we write it this way?
```suggestion
	/** Snackbar instance. */
	private readonly snackBar: MatSnackBar = inject(MatSnackBar);
```

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/user.service.ts
> +	public readonly isUserLoggedIn$: Observable<boolean> = this.userSecretService.secret$.pipe(
```suggestion
	public readonly isUserLoggedIn$ = this.userSecretService.secret$.pipe(
```

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/user.service.ts
> +			map(() => void 0),
Prefer using `undefined`. `void 0` is basically another way to get `undefined`, so there's no benefit in using

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/shared/components/the-header/the-header.component.ts
I think `the-` is vague. I suggest naming it `page-header`, it shows that it's a header for pages.

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on libs/core/mappers/api-error.mapper.ts
> +const USER_FRIENDLY_ERROR_ATTRS = ['email', 'password', 'first_name', 'last_name', 'avatar'];
Not sure what `friendly` means. I think it's okay to name it just `USER_ERROR_CODES/ATTRS`

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on libs/core/mappers/api-error.mapper.ts
> +const GENERAL_ERROR_MESSAGE = 'Something went wrong. Please try again later.';
"General" is okay, but we usually use "default" term

2024-08-09 04:59 UTC, artem-sotnichenko-saritasa commented on libs/core/mappers/registration.mapper.ts
> +			/* eslint-disable @typescript-eslint/naming-convention */
Let's update our eslint configuration and disable `naming-convention` for all `*.mapper.ts` files

2024-08-09 05:07 UTC, sherstkov commented on apps/angular/src/app/features/authentification/login/login.component.ts
> +				takeUntilDestroyed(this.destroyRef),
I'm sorry, but can you clarify where you prefer to place `takeUntilDestroyed(this.destroyRef)`?

2024-08-12 04:13 UTC, viktor-sakhno-saritasa approved these changes

2024-08-12 04:13 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/authentification/auth.component.ts
>  }
Sorry, I didn't see that you use `router.url` which is synchronous. Your previous decision was good :) Signals are overhead here.

2024-08-12 04:13 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/authentification/input-password/input-password.component.ts
> +		this.hidePassword.set(!this.hidePassword());
```suggestion
		this.hidePassword.update(previousvalue => !previousValue);
```

2024-08-12 04:13 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/authentification/register/register.component.html
> +		<div [formGroup]="registerForm.controls.passwordGroup" class="password-group">
Let's use semantic tag `form` instead `div`?

2024-08-12 08:15 UTC, viktor-sakhno-saritasa approved these changes

2024-08-12 08:47 UTC, artem-sotnichenko-saritasa approved these changes

2024-08-12 08:47 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/authentification/auth.component.ts
> +/** Auth component for styles. */
Can you explain what "for styles" mean?
```suggestion
/** Auth component. */
```

2024-08-12 08:47 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/authentification/login/login.component.ts
> +				_ => this.router.navigate([URL_PATHS.home]),
If all arguments are unused, we prefer an empty arguments array.
```suggestion
				() => this.router.navigate([URL_PATHS.home]),
```

2024-08-12 09:01 UTC, sherstkov commented on apps/angular/src/app/features/authentification/auth.component.ts
> +/** Auth component for styles. */
At first this component should be `dumb` with no logic. Just for style purposes. Deleted this comment for now :+1:

2024-08-14 07:06 UTC, DaniilMaslovSaritasa approved these changes

2024-08-15 12:45 UTC, pavelzadorin-saritasa requested changes

2024-08-15 12:45 UTC, pavelzadorin-saritasa commented on libs/core/models/registration.ts
> +export class Registration extends Immerable {
Try to think about the model as if it were an object in the real world. Registration is not an object, it is a process as a result of which we create a user, I think your model just describes the user object and should be named accordingly.

2024-08-16 00:59 UTC, sherstkov commented on libs/core/models/registration.ts
> +export class Registration extends Immerable {
Completely agree. I changed for `Registration/LoginCredentials` but maybe `UserRegistrationData` is more precise?

2024-08-18 16:53 UTC, andrey-gazzaev approved these changes

2024-08-18 16:53 UTC, andrey-gazzaev commented on apps/angular/src/core/services/api-url.service.ts
> +		this.loginPath = `${this.appConfig.apiUrl}/auth/login/`;
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

2024-08-18 16:53 UTC, andrey-gazzaev commented on apps/angular/src/core/services/auth.service.ts
> +	}
This looks like something you might need to use multiple times. Try making your own rxjs operator.https://angularindepth.com/posts/1421/rxjs-custom-operators

2024-08-19 07:31 UTC, pavelzadorin-saritasa commented on libs/core/models/registration.ts
> +export class Registration extends Immerable {
`UserRegistration` would be a better option. To register a user, we actually have to send all the data of the user; most likely it will be exactly the same model as we will receive from the API for already registered users plus a password. I.e. I see the following model structure here: User (all fields except the password) and UserRegistration (inherits User and adds a password)
But since we don't need simple User right now we can leave your current implementation.

2024-08-19 07:32 UTC, pavelzadorin-saritasa approved these changes

2024-08-21 11:54 UTC, merged