Feature/jc 688 details page
saritasa-nest/camp-js-2024-maxim-sherstkov pull request #6
Opened 2024-08-13 05:31 UTC by sherstkov

Created details page

2024-08-14 04:35 UTC, SofyaKirillova requested changes

2024-08-14 04:35 UTC, SofyaKirillova commented on libs/core/models/anime-details.ts
> +export class AnimeDetails extends Immerable {
Many fields are duplicated with the `Anime` model. Let's do something about it.

2024-08-14 04:35 UTC, SofyaKirillova commented on libs/core/models/anime-details.ts
> +	/** Image of the anime. */
```suggestion
	/** Image source. */
```

2024-08-14 04:35 UTC, SofyaKirillova commented on libs/core/models/anime-details.ts
> +	public readonly genresData: readonly Genre[];
```suggestion
	/** Studios data. */
	public readonly studiosData: readonly Studio[];

	/** Genres data. */
	public readonly genresData: readonly Genre[];
```

2024-08-14 04:35 UTC, SofyaKirillova commented on apps/angular/src/core/guards/auth.guard.ts
> + * @param _route Activated route.
```suggestion
 * Checks user's access to a route.
 * @param _route Activated route.
```

2024-08-14 04:35 UTC, SofyaKirillova commented on apps/angular/src/app/features/anime-details/anime-details.component.html
> +			<mat-card *ngIf="animeDetails$ | async as animeDetails" class="anime-details">
why is `if` repeated with the same conditions?

2024-08-14 04:35 UTC, SofyaKirillova commented on apps/angular/src/app/features/anime-details/anime-details.component.html
> +					<mat-card-title><h1>{{animeDetails.japaneseTitle}}</h1></mat-card-title>
```suggestion
					<mat-card-title>
						<h1>{{animeDetails.japaneseTitle}}</h1>
					</mat-card-title>
```

2024-08-14 04:35 UTC, SofyaKirillova commented on apps/angular/src/app/features/anime-details/anime-details.component.html
> +								}
Let's create a method for this

2024-08-14 04:35 UTC, SofyaKirillova commented on apps/angular/src/app/features/anime-details/anime-details.component.html
> +							<ng-container *ngIf="showTrailer()">
Let's use `@if` or `ngIf`

2024-08-14 04:35 UTC, SofyaKirillova commented on apps/angular/src/shared/components/image-dialog/image-dialog.component.html
Let's remove the scroll
![image](https://github.com/user-attachments/assets/b1505848-5a22-4cc4-8fcb-2e0638080fac)

2024-08-19 02:38 UTC, SofyaKirillova approved these changes

2024-08-19 02:38 UTC, SofyaKirillova commented on libs/core/dtos/anime.dto.ts
>  	/** Airing. */
```suggestion
	/** Is airing. */
```

2024-08-19 02:38 UTC, SofyaKirillova commented on libs/core/models/anime-details.ts
>  	/** Airing. */
```suggestion
	/** Is airing. */
```

2024-08-19 12:58 UTC, timofei-maximov-saritasa approved these changes

2024-08-20 08:12 UTC, pavelzadorin-saritasa commented on libs/core/mappers/anime.mapper.ts
>  	export function fromDto(dto: AnimeDto): Anime {
you use AnimeDto to describe anime in the list API, but the DTO in the list is much narrower than what is currently described in AnimeDto, this is an incorrect typing that can be misleading.

2024-08-20 08:16 UTC, pavelzadorin-saritasa commented on libs/core/models/anime.ts
> +export class Anime extends AnimeBase {
You got the suffix “Detailed” then what is just Anime now? Is it more than "Detailed" or lesser?
Since you now have several types of Anime in the model, they should all have suffixes indicating their features.

2024-08-20 08:17 UTC, pavelzadorin-saritasa commented on libs/core/models/anime.ts
>  	public readonly airedStart: Date | null;
Detailed Anime also contains this information, if we do not duplicate this information then we can get rid of the whole model.

2024-08-20 08:18 UTC, pavelzadorin-saritasa commented on libs/core/models/date-time-range-field.ts
> +export type DateTimeRangeField = {
the same comment like for Dto

2024-08-20 08:21 UTC, pavelzadorin-saritasa commented on libs/core/models/anime-details.ts
> +	public readonly studiosData: readonly Studio[];
`Data` is meaningless suffix in 99% cases, what additional info it give us here?

2024-08-20 08:23 UTC, pavelzadorin-saritasa commented on libs/core/mappers/studio.mapper.ts
> +	export function fromDtoArray(dtoArray: readonly StudioDto[]): readonly Studio[] {
Looks like a good candidate to extract to generic function to not repeat this code twice.

2024-08-28 07:39 UTC, pavelzadorin-saritasa approved these changes

2024-08-28 09:40 UTC, merged